# netlify.toml
[build]
  base = "ecommerce-frontend"
  command = "npm run build"
  publish = "ecommerce-frontend/dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
